### ISSUE TITLE
Help needed to setup the MNIST-DVS dataset

### ISSUE THREAD

**Issue by yeshwanthv5** [kclip/FL-SNN#1]
Hello Authors

Thanks a lot for open sourcing the code for this paper. I am trying to reproduce the results by running mnist_test.py. Can you please share the process to generate the hdf5 dataset in the format that is used by the code.

Thank you

**Comment by nskat** [comment]
Hi,
Thank you for your interest in our work! You can find it in this repo: https://github.com/kclip/snn
I hope this helps.
Nicolas

**Comment by yeshwanthv5** [comment]
Thanks a lot :)
